[tool.black]
line-length = 120
extend-ignore = "E203"
skip-magic-trailing-comma = true

[tool.flake8]
ignore = "D100, D104, E203, W503"
max-line-length = 120
max-complexity = 10
ban-relative-imports = true
exclude = ["__pycache__", "venv/"]
per-file-ignores = []

[tool.isort]
profile = "black"
line_length = 120
